using System;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Networking;
using NativeWebSocket;
using System.Collections;
using UnityEditor.PackageManager;


public class GameNetworkManager : MonoBehaviour
{

    private WebSocket websocket;


    private String host;
    private String urlString;
    private DateTime requestStartTime;

    private int serverPort = 8000;

    // public PlayerManager playerManager;
    // public BulletManager bulletManager;
    // public ItemManager itemManager;
    // public GameStateManager gameStateManager;

    void Start()
    {

        InitializeAndConnect();

        if (Debug.isDebugBuild)
        {
            InvokeRepeating(nameof(SendHttpPing), 1f, 10f);
        }

        // ì›¹ì†Œì¼“ ì—°ê²°
        // webSocketClient.OnMessageReceived += OnDataReceived;
        // webSocketClient.Connect("ws://your-server-address");
    }

    public void Update()
    {
        // NativeWebsocketì—ì„œëŠ” ì´ ì½”ë“œê°€ í•„ìš”í•©ë‹ˆë‹¤.
#if !UNITY_WEBGL || UNITY_EDITOR
        websocket?.DispatchMessageQueue();
#endif
    }

    private void OnApplicationQuit()
    {
        Close();
    }
    public async void InitializeAndConnect()
    {
        Debug.Log($"ğŸ’© Init Network");

        if (!Debug.isDebugBuild)
        {

            // TODO: ì„œë²„ ë°°í¬ í›„ì—ëŠ” Hostë¥¼ DomainNameìœ¼ë¡œ ë°”ê¿”ì•¼ í•¨

            var url = Application.absoluteURL;

            Debug.LogError($"ğŸ’© Try: {url}");

            try
            {
                Uri uri = new Uri(url);
                host = uri.Host; // í˜¸ìŠ¤íŠ¸ ì˜ì—­ ì¶”ì¶œ

                // í¬íŠ¸ë¥¼ 8000ìœ¼ë¡œ ì„¤ì •
                UriBuilder uriBuilder = new UriBuilder(uri)
                {
                    Port = serverPort // í¬íŠ¸ë¥¼ 8000ìœ¼ë¡œ ì„¤ì •
                };

                // URL ë³€ê²½
                url = uriBuilder.ToString();
            }
            catch (UriFormatException e)
            {
                Debug.LogError($"Invalid URL format: {e.Message}");
            }

            if (url.StartsWith("https://"))
            {
                url = url.Replace("https://", "wss://");
            }
            else if (url.StartsWith("http://"))
            {
                url = url.Replace("http://", "ws://");
            }

            urlString = url; // ì‹¤ì œ ì›¹ì•±ì—ì„œ ë„˜ì–´ì˜¬ ë•Œì—ëŠ” ê²½ë¡œì™€ ì¿¼ë¦¬ìŠ¤íŠ¸ë§ì´ ê°™ì´ ë„˜ì–´ì˜¨ë‹¤.
        }
        else
        {
            urlString = $"ws://localhost:{serverPort}/room?roomId=test&clientId=test";
            host = $"localhost:{serverPort}";
        }
        Debug.Log($"Initializing WebSocket with URL: {urlString}");
        websocket = new WebSocket(urlString);

        websocket.OnOpen += onOpen;
        websocket.OnMessage += OnMessage;
        websocket.OnClose += OnClose;
        websocket.OnError += OnError;

        try
        {
            await websocket.Connect();
        }
        catch (Exception ex)
        {
            Debug.LogError($"Failed to connect WebSocket: {ex.Message}");
        }
    }


    public async void Close()
    {
        if (websocket == null)
        {
            Debug.LogWarning("WebSocket is not initialized.");
            return;
        }

        if (websocket.State == WebSocketState.Closed || websocket.State == WebSocketState.Closing)
        {
            Debug.LogWarning("WebSocket is already closed or closing.");
            return;
        }

        try
        {
            await websocket.Close();
        }
        catch (Exception ex)
        {
            Debug.LogError($"Failed to close WebSocket: {ex.Message}");
        }
    }

    private void onOpen()
    {
        Debug.Log($"Connection open! : {urlString}");
    }

    private void OnError(string errorMsg)
    {
        Debug.Log($"Error! {errorMsg}");
    }

    private void OnClose(WebSocketCloseCode OnClose)
    {
        Debug.Log("Connection closed!");
    }

    private void OnMessage(byte[] data)
    {
        // ì„œë²„ ë°ì´í„° íŒŒì‹±
        // ServerData serverData = JsonUtility.FromJson<ServerData>(jsonData);

        // ê²Œì„ ìƒíƒœ ì²˜ë¦¬
        // gameStateManager.ProcessGameState(serverData.gameState);

        // ê° ë§¤ë‹ˆì €ì— ë°ì´í„° ì „ë‹¬
        // playerManager.UpdatePlayers(serverData.players);
        // bulletManager.UpdateBullets(serverData.bullets);
        // itemManager.UpdateItems(serverData.items);
    }


    private void SendHttpPing()
    {
        StartCoroutine(SendHttpPingCoroutine());
    }

    private IEnumerator SendHttpPingCoroutine()
    {
        // ìš”ì²­ ì‹œì‘ ì‹œê°„ ê¸°ë¡
        requestStartTime = DateTime.Now;

        using (UnityWebRequest request = UnityWebRequest.Get("http://" + host + "/ping"))
        {
            yield return request.SendWebRequest(); // ìš”ì²­ ë³´ë‚´ê¸°

            // ìš”ì²­ ì™„ë£Œ ì‹œê°„
            DateTime requestEndTime = DateTime.Now;
            long latency = (long)(requestEndTime - requestStartTime).TotalMilliseconds; // ë ˆì´í„´ì‹œ ê³„ì‚°

            if (request.result == UnityWebRequest.Result.Success)
            {
                Debug.Log($"HTTP Ping success. RTT: {latency} ms");

                // EventBusë¥¼ í†µí•´ ë ˆì´í„´ì‹œ ì „ë‹¬
                EventBus<InGameGUIEventType>.Publish(InGameGUIEventType.UpdatePingLabel, latency);
            }
            else
            {
                Debug.LogError($"HTTP Ping failed: {request.error}");
            }
        }
    }
}
